-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid,
  user_id uuid,
  project_id uuid,
  action character varying NOT NULL,
  action_category character varying NOT NULL,
  details jsonb DEFAULT '{}'::jsonb,
  user_email character varying,
  user_name character varying,
  org_name character varying,
  project_name character varying,
  sf_amount integer,
  amount_cents integer,
  status character varying DEFAULT 'success'::character varying,
  error_message text,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT activity_logs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.email_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  to_email text NOT NULL,
  to_name text,
  subject text NOT NULL,
  template_type text NOT NULL,
  template_data jsonb NOT NULL,
  attachment_url text,
  attachment_name text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sending'::text, 'sent'::text, 'failed'::text])),
  error_message text,
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 3,
  scheduled_for timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_queue_pkey PRIMARY KEY (id),
  CONSTRAINT email_queue_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.estimate_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  share_id uuid NOT NULL,
  response_type text NOT NULL CHECK (response_type = ANY (ARRAY['question'::text, 'comment'::text, 'approval'::text, 'rejection'::text])),
  message text,
  signature_data jsonb,
  client_name text,
  ip_address text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT estimate_responses_pkey PRIMARY KEY (id),
  CONSTRAINT estimate_responses_share_id_fkey FOREIGN KEY (share_id) REFERENCES public.estimate_shares(id)
);
CREATE TABLE public.estimate_share_views (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  share_id uuid NOT NULL,
  viewed_at timestamp with time zone DEFAULT now(),
  ip_address text,
  user_agent text,
  referrer text,
  CONSTRAINT estimate_share_views_pkey PRIMARY KEY (id),
  CONSTRAINT estimate_share_views_share_id_fkey FOREIGN KEY (share_id) REFERENCES public.estimate_shares(id)
);
CREATE TABLE public.estimate_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  organization_id uuid,
  share_token text NOT NULL UNIQUE,
  client_name text,
  client_email text,
  client_phone text,
  expires_at timestamp with time zone,
  password_hash text,
  view_count integer DEFAULT 0,
  last_viewed_at timestamp with time zone,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'viewed'::text, 'approved'::text, 'rejected'::text, 'expired'::text])),
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone,
  signature_data jsonb,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sms_verification_required boolean NOT NULL DEFAULT false,
  sms_verified_at timestamp with time zone,
  sms_verified_phone_last4 text,
  sms_otp_hash text,
  sms_otp_expires_at timestamp with time zone,
  sms_attempts integer DEFAULT 0,
  email_verification_required boolean DEFAULT false,
  email_otp_hash text,
  email_otp_expires_at timestamp with time zone,
  email_otp_attempts integer DEFAULT 0,
  email_verified_at timestamp with time zone,
  CONSTRAINT estimate_shares_pkey PRIMARY KEY (id),
  CONSTRAINT estimate_shares_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT estimate_shares_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT estimate_shares_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.estimate_signature_evidence (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  share_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['viewed'::text, 'sms_sent'::text, 'sms_verified'::text, 'sms_failed'::text, 'signed'::text, 'approved'::text, 'rejected'::text, 'downloaded'::text])),
  ip_address inet,
  user_agent text,
  referrer text,
  geo jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT estimate_signature_evidence_pkey PRIMARY KEY (id),
  CONSTRAINT estimate_signature_evidence_share_id_fkey FOREIGN KEY (share_id) REFERENCES public.estimate_shares(id)
);
CREATE TABLE public.estimates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text,
  labor_hours numeric,
  labor_rate numeric,
  materials_cost numeric,
  equipment_cost numeric,
  markup_percent numeric,
  subtotal numeric,
  tax numeric,
  total numeric,
  pricing_breakdown jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT estimates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.material_costs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  material_type text NOT NULL,
  material_name text NOT NULL,
  sku text,
  unit text NOT NULL,
  cost_per_unit numeric NOT NULL,
  supplier text,
  supplier_sku text,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT material_costs_pkey PRIMARY KEY (id),
  CONSTRAINT material_costs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.notification_preferences (
  user_id uuid NOT NULL,
  email_estimate_approved boolean DEFAULT true,
  email_estimate_rejected boolean DEFAULT true,
  email_estimate_viewed boolean DEFAULT false,
  email_estimate_question boolean DEFAULT true,
  email_sf_pool_low boolean DEFAULT true,
  sf_pool_warning_threshold integer DEFAULT 5,
  email_team_activity boolean DEFAULT false,
  email_new_member_joined boolean DEFAULT true,
  email_project_assigned boolean DEFAULT true,
  email_project_archived boolean DEFAULT false,
  digest_frequency text DEFAULT 'instant'::text CHECK (digest_frequency = ANY (ARRAY['instant'::text, 'daily'::text, 'weekly'::text, 'none'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (user_id),
  CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.org_domain_rules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  domain character varying NOT NULL,
  default_role character varying NOT NULL DEFAULT 'member'::character varying CHECK (default_role::text = ANY (ARRAY['admin'::character varying, 'member'::character varying, 'viewer'::character varying]::text[])),
  enabled boolean DEFAULT true,
  verified_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT org_domain_rules_pkey PRIMARY KEY (id),
  CONSTRAINT org_domain_rules_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT org_domain_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.org_invites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  email character varying,
  token character varying NOT NULL UNIQUE,
  role character varying NOT NULL DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['admin'::character varying, 'member'::character varying, 'viewer'::character varying]::text[])),
  invite_type character varying NOT NULL DEFAULT 'email'::character varying CHECK (invite_type::text = ANY (ARRAY['email'::character varying, 'link'::character varying, 'domain'::character varying]::text[])),
  invited_by uuid NOT NULL,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '7 days'::interval),
  accepted_at timestamp with time zone,
  revoked_at timestamp with time zone,
  max_uses integer DEFAULT 1,
  use_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT org_invites_pkey PRIMARY KEY (id),
  CONSTRAINT org_invites_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT org_invites_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['owner'::character varying, 'admin'::character varying, 'member'::character varying, 'viewer'::character varying]::text[])),
  invited_by uuid,
  joined_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  logo_url text,
  plan character varying NOT NULL DEFAULT 'free'::character varying CHECK (plan::text = ANY (ARRAY['free'::character varying, 'trial'::character varying, 'paid'::character varying, 'enterprise'::character varying]::text[])),
  billing_status character varying DEFAULT 'inactive'::character varying CHECK (billing_status::text = ANY (ARRAY['inactive'::character varying, 'active'::character varying, 'past_due'::character varying, 'canceled'::character varying]::text[])),
  billing_owner_id uuid,
  stripe_customer_id character varying,
  stripe_subscription_id character varying,
  trial_ends_at timestamp with time zone,
  settings jsonb DEFAULT '{}'::jsonb,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  sf_pool_total integer DEFAULT 0,
  sf_pool_used integer DEFAULT 0,
  sf_pool_updated_at timestamp with time zone DEFAULT now(),
  require_signup_phone_verification boolean DEFAULT false,
  require_estimate_sms_verification boolean DEFAULT false,
  sms_settings jsonb DEFAULT '{}'::jsonb,
  promo_project_credits integer DEFAULT 0,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_billing_owner_id_fkey FOREIGN KEY (billing_owner_id) REFERENCES public.users(id),
  CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.project_bom (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  material_cost_id uuid,
  material_type text NOT NULL,
  material_name text NOT NULL,
  quantity numeric NOT NULL,
  unit text NOT NULL,
  unit_cost numeric,
  total_cost numeric,
  is_auto_calculated boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_bom_pkey PRIMARY KEY (id),
  CONSTRAINT project_bom_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_bom_material_cost_id_fkey FOREIGN KEY (material_cost_id) REFERENCES public.material_costs(id)
);
CREATE TABLE public.project_collaborators (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL DEFAULT 'collaborator'::character varying CHECK (role::text = ANY (ARRAY['collaborator'::character varying, 'viewer'::character varying]::text[])),
  invited_by uuid NOT NULL,
  invited_at timestamp with time zone NOT NULL DEFAULT now(),
  accepted_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_collaborators_pkey PRIMARY KEY (id),
  CONSTRAINT project_collaborators_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_collaborators_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT project_collaborators_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.project_estimates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  materials_cost numeric,
  labor_cost numeric,
  permits_fees numeric,
  contingency numeric,
  total_cost numeric DEFAULT (((COALESCE(materials_cost, (0)::numeric) + COALESCE(labor_cost, (0)::numeric)) + COALESCE(permits_fees, (0)::numeric)) + COALESCE(contingency, (0)::numeric)),
  notes text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  organization_id uuid,
  CONSTRAINT project_estimates_pkey PRIMARY KEY (id),
  CONSTRAINT project_estimates_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_estimates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.project_revenue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL UNIQUE,
  organization_id uuid,
  estimated_revenue numeric,
  actual_revenue numeric,
  estimated_cost numeric,
  actual_cost numeric,
  margin_percent numeric,
  payment_status text DEFAULT 'unpaid'::text CHECK (payment_status = ANY (ARRAY['unpaid'::text, 'partial'::text, 'paid'::text])),
  invoice_number text,
  invoice_sent_at timestamp with time zone,
  paid_at timestamp with time zone,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_revenue_pkey PRIMARY KEY (id),
  CONSTRAINT project_revenue_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_revenue_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  organization_id uuid,
  payment_required boolean DEFAULT true,
  payment_completed boolean DEFAULT false,
  payment_id text,
  archived_at timestamp with time zone,
  archived_by uuid,
  address text,
  city text,
  state text,
  zip_code text,
  latitude double precision,
  longitude double precision,
  postal_code text,
  square_footage numeric,
  roof_data jsonb,
  roof_data_status text,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT projects_archived_by_fkey FOREIGN KEY (archived_by) REFERENCES auth.users(id)
);
CREATE TABLE public.promo_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key_code character varying NOT NULL UNIQUE,
  is_used boolean NOT NULL DEFAULT false,
  used_by_user_id uuid,
  used_for_project_id uuid,
  used_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by text,
  metadata jsonb DEFAULT '{}'::jsonb,
  notes text,
  credits_total integer DEFAULT 1,
  credits_remaining integer DEFAULT 1,
  organization_id uuid,
  CONSTRAINT promo_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sf_pool_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  project_id uuid,
  transaction_type character varying NOT NULL CHECK (transaction_type::text = ANY (ARRAY['purchase'::character varying, 'usage'::character varying, 'refund'::character varying, 'adjustment'::character varying]::text[])),
  sf_amount integer NOT NULL,
  sf_balance_after integer NOT NULL,
  price_cents integer,
  stripe_payment_id character varying,
  stripe_session_id character varying,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sf_pool_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT sf_pool_transactions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT sf_pool_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT sf_pool_transactions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.signup_email_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  otp_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  attempts integer DEFAULT 0,
  verified_at timestamp with time zone,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT signup_email_verifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.signup_phone_verifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL,
  phone text NOT NULL,
  otp_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  attempts integer DEFAULT 0,
  verified_at timestamp with time zone,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT signup_phone_verifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sms_delivery_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  message_sid text NOT NULL,
  messaging_service_sid text,
  to_phone text,
  from_phone text,
  message_status text NOT NULL,
  error_code text,
  error_message text,
  share_id uuid,
  share_token text,
  CONSTRAINT sms_delivery_events_pkey PRIMARY KEY (id),
  CONSTRAINT sms_delivery_events_share_id_fkey FOREIGN KEY (share_id) REFERENCES public.estimate_shares(id)
);
CREATE TABLE public.stripe_customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  stripe_customer_id text NOT NULL UNIQUE,
  email text NOT NULL,
  name text,
  phone text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_customers_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.stripe_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  stripe_invoice_id text NOT NULL UNIQUE,
  stripe_customer_id text NOT NULL,
  stripe_subscription_id text,
  stripe_payment_intent_id text,
  number text,
  status text NOT NULL,
  amount_due integer NOT NULL,
  amount_paid integer DEFAULT 0,
  amount_remaining integer DEFAULT 0,
  subtotal integer NOT NULL,
  total integer NOT NULL,
  tax integer DEFAULT 0,
  currency text DEFAULT 'usd'::text,
  invoice_date timestamp with time zone,
  due_date timestamp with time zone,
  paid_at timestamp with time zone,
  invoice_pdf text,
  hosted_invoice_url text,
  attempted boolean DEFAULT false,
  attempt_count integer DEFAULT 0,
  next_payment_attempt timestamp with time zone,
  description text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_invoices_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_stripe_customer FOREIGN KEY (stripe_customer_id) REFERENCES public.stripe_customers(stripe_customer_id),
  CONSTRAINT fk_stripe_subscription FOREIGN KEY (stripe_subscription_id) REFERENCES public.stripe_subscriptions(stripe_subscription_id)
);
CREATE TABLE public.stripe_payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  stripe_customer_id text NOT NULL,
  stripe_payment_method_id text NOT NULL UNIQUE,
  type text NOT NULL,
  is_default boolean DEFAULT false,
  card_brand text,
  card_last4 text,
  card_exp_month integer,
  card_exp_year integer,
  card_country text,
  bank_name text,
  bank_last4 text,
  bank_account_type text,
  billing_name text,
  billing_email text,
  billing_phone text,
  billing_address_line1 text,
  billing_address_line2 text,
  billing_address_city text,
  billing_address_state text,
  billing_address_postal_code text,
  billing_address_country text,
  status text DEFAULT 'active'::text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_payment_methods_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_payment_methods_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_stripe_customer FOREIGN KEY (stripe_customer_id) REFERENCES public.stripe_customers(stripe_customer_id)
);
CREATE TABLE public.stripe_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  project_id uuid,
  stripe_payment_intent_id text UNIQUE,
  stripe_charge_id text,
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_invoice_id text,
  amount integer NOT NULL,
  amount_received integer,
  currency text DEFAULT 'usd'::text,
  status text NOT NULL,
  payment_method_type text,
  payment_method_last4 text,
  payment_method_brand text,
  payment_type text NOT NULL,
  description text,
  receipt_url text,
  receipt_email text,
  refunded boolean DEFAULT false,
  refund_amount integer DEFAULT 0,
  refund_reason text,
  refunded_at timestamp with time zone,
  failure_code text,
  failure_message text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_payments_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT stripe_payments_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT fk_stripe_customer FOREIGN KEY (stripe_customer_id) REFERENCES public.stripe_customers(stripe_customer_id),
  CONSTRAINT fk_stripe_subscription FOREIGN KEY (stripe_subscription_id) REFERENCES public.stripe_subscriptions(stripe_subscription_id)
);
CREATE TABLE public.stripe_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  stripe_subscription_id text NOT NULL UNIQUE,
  stripe_customer_id text NOT NULL,
  status text NOT NULL,
  price_id text,
  product_id text,
  amount integer NOT NULL,
  currency text DEFAULT 'usd'::text,
  interval text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  trial_start timestamp with time zone,
  trial_end timestamp with time zone,
  cancel_at timestamp with time zone,
  canceled_at timestamp with time zone,
  ended_at timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  cancellation_reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT stripe_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT stripe_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT fk_stripe_customer FOREIGN KEY (stripe_customer_id) REFERENCES public.stripe_customers(stripe_customer_id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  org_id uuid,
  project_id uuid,
  type text NOT NULL DEFAULT 'roof_verification_rejected'::text,
  reason text,
  address text,
  metadata jsonb DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'open'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT support_tickets_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  active_org_id uuid,
  company_name text,
  company_logo_url text,
  company_phone text,
  company_address text,
  company_email text,
  company_website text,
  phone text,
  phone_verified_at timestamp with time zone,
  phone_otp_hash text,
  phone_otp_expires_at timestamp with time zone,
  phone_otp_attempts integer DEFAULT 0,
  tutorial_state jsonb DEFAULT '{"skipped": false, "completed": false, "startedAt": null, "currentStep": 0, "dismissedAt": null, "completedSteps": []}'::jsonb,
  promo_project_credits integer DEFAULT 0,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_active_org_id_fkey FOREIGN KEY (active_org_id) REFERENCES public.organizations(id)
);o